#!/bin/bash

sudo yum update -y
sudo yum install epel-release yum-utils -y
#if you are using centOs 7
sudo yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm
sudo yum-config-manager --enable remi-php81

#if you are using centos 8
# yum install http://rpms.remirepo.net/enterprise/remi-release-8.rpm
# yum module enable php:remi-8.1
sudo yum update
sudo yum install php

sudo php -v
